name: 🔬 Neural Activity Tracker

on:
  schedule:
    - cron: "0 4 * * *" # Daily at 4:00 AM UTC
    - cron: "0 16 * * *" # Daily at 4:00 PM UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-current-action:
    runs-on: ubuntu-latest
    name: 🧠 Analyze Neural Patterns

    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        uv-version: ["0.6.16"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ matrix.uv-version }}
          enable-cache: true
      - name: 🧠 Check current action
        run: |
          uv run python src/main.py

      - name: 🔄 Update repository with fresh visuals
        run: |
          git config --local user.email "jorge@menjivar.ai"
          git config --local user.name "Quantum Activity Bot"
          git add assets/
          git diff --staged --quiet || git commit -m "🧠 Quantum activity patterns updated"
          git push
